import { Geist, Geist_Mono } from "next/font/google";
import  {SidebarProvider, SidebarTrigger} from "@/components/ui/sidebar";
import {AppSidebar} from "@/components/app-sidebar";
import "./globals.css";
import Image from "next/image";
import {
    NavigationMenu,
    NavigationMenuContent, NavigationMenuItem, NavigationMenuLink,
    NavigationMenuList,
    NavigationMenuTrigger
} from "@/components/ui/navigation-menu";
import Nav from "@/components/nav"
import LoginButton from "@/components/googleLogin";
import AuthProvider from "@/components/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SASA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
    <body className="h-screen">
        <AuthProvider>
                <Nav/>
                {children}
        </AuthProvider>
      </body>
    </html>
  );
}


